package main;

import flat.Flat;
import flat.uxml.Controller;

public class LazyController extends Controller {
    @Flat
    public void onChangeLocale() {

    }
}
/*

UPDATE BT_Block
SET BlockReference = CONCAT(Workid2, 'ABCDEFGHIJKNLMNOPQRTUVWXYZABCDEFGHIJKNLMNOPQRTUVWXYZ')

UPDATE BT_DayMapLastTimepointTime SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE BT_RunBlock SET WorkId2 = CONCAT(WorkId2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkId2 IS NOT NULL;
UPDATE BT_Schedule SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE BT_ScheduleData SET WorkId2 = CONCAT(WorkId2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkId2 IS NOT NULL;
UPDATE BT_TripDetail SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_DS_Transaction_Details SET NewWorkID2 = CONCAT(NewWorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE NewWorkID2 IS NOT NULL;
UPDATE CC_DS_Transaction_Details SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_Event SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_Incident SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_IncidentRelief SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_LogonInfo SET WorkId2 = CONCAT(WorkId2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkId2 IS NOT NULL;
UPDATE CC_MailRequest SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_MailTransmission SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_ScheduleService SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_SDSOUpdate_Timepoint SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE CC_SpecOpInstance SET Vehicle1WorkID2 = CONCAT(Vehicle1WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE Vehicle1WorkID2 IS NOT NULL;
UPDATE CC_SpecOpInstance SET Vehicle2WorkID2 = CONCAT(Vehicle2WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE Vehicle2WorkID2 IS NOT NULL;
UPDATE DS_PublishedTrainSavedState SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE DS_RunBlock SET WorkId2 = CONCAT(WorkId2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkId2 IS NOT NULL;
UPDATE DS_TripDetail SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE LOG_AutomatedLogon SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE LOG_BT_RunBlock SET WorkId2 = CONCAT(WorkId2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkId2 IS NOT NULL;
UPDATE LOG_Event SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE LOG_SpecOpCarveBlockHistory SET FirstTailWorkID2 = CONCAT(FirstTailWorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE FirstTailWorkID2 IS NOT NULL;
UPDATE LOG_SpecOpCarveBlockHistory SET LastHeadWorkID2 = CONCAT(LastHeadWorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE LastHeadWorkID2 IS NOT NULL;
UPDATE LOG_SpecOpCarveBlockHistory SET NormalTripWorkID2 = CONCAT(NormalTripWorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE NormalTripWorkID2 IS NOT NULL;
UPDATE LOG_SpecOpCarveBlockHistory SET ReliefTripWorkID2 = CONCAT(ReliefTripWorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE ReliefTripWorkID2 IS NOT NULL;
UPDATE LOG_SpecOpCarveBlockHistory SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE LOG_SpecOpInstance SET Vehicle1WorkID2 = CONCAT(Vehicle1WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE Vehicle1WorkID2 IS NOT NULL;
UPDATE LOG_SpecOpInstance SET Vehicle2WorkID2 = CONCAT(Vehicle2WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE Vehicle2WorkID2 IS NOT NULL;
UPDATE LOG_SpecOpsCarve_RunBlockInfo SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE LOG_VoiceCallController SET WorkID2 = CONCAT(WorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkID2 IS NOT NULL;
UPDATE RunBlockBreaks SET NextWorkID2 = CONCAT(NextWorkID2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE NextWorkID2 IS NOT NULL;
UPDATE RunBlockBreaks SET WorkId2 = CONCAT(WorkId2, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') WHERE WorkId2 IS NOT NULL;

 */