/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class flat_backend_SVG */

#ifndef _Included_flat_backend_SVG
#define _Included_flat_backend_SVG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     flat_backend_SVG
 * Method:    Init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_flat_backend_SVG_Init
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    Finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Finish
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    BeginFrame
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_BeginFrame
  (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    CancelFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_CancelFrame
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    EndFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_EndFrame
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    SetGlobalCompositeOperation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetGlobalCompositeOperation
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetGlobalCompositeBlendFunction
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetGlobalCompositeBlendFunction
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    StateSave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_StateSave
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    StateRestore
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_StateRestore
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    StateReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_StateReset
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    SetShapeAntiAlias
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetShapeAntiAlias
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetStrokeColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetStrokeColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFillColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFillColor
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetMiterLimit
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetMiterLimit
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetStrokeWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetStrokeWidth
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetLineCap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetLineCap
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetLineJoin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetLineJoin
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetGlobalAlpha
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetGlobalAlpha
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformIdentity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformIdentity
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformSet
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformSet
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformTranslate
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformTranslate
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformRotate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformRotate
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformSkewX
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformSkewX
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformSkewY
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformSkewY
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformScale
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformScale
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformGetCurrent
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformGetCurrent
  (JNIEnv *, jclass, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    SetScissor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetScissor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetIntersectScissor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetIntersectScissor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    ResetScissor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_ResetScissor
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    BeginPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_BeginPath
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    MoveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_MoveTo
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    LineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_LineTo
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    BezierTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_BezierTo
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    QuadTo
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_QuadTo
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    ArcTo
 * Signature: (FFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_ArcTo
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    ClosePath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_ClosePath
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    PathWinding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_PathWinding
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    Arc
 * Signature: (FFFFFI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Arc
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    Rect
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Rect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    RoundedRect
 * Signature: (FFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_RoundedRect
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Ellipse
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Ellipse
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Circle
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Circle
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Fill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Fill
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    Stroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Stroke
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    FontCreate
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontCreate
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     flat_backend_SVG
 * Method:    FontFind
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontFind
  (JNIEnv *, jclass, jstring);

/*
 * Class:     flat_backend_SVG
 * Method:    FontDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    FontAddFallbackFont
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_flat_backend_SVG_FontAddFallbackFont
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    TextSetFont
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TextSetFont
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    TextSetSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TextSetSize
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TextSetBlur
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TextSetBlur
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TextSetLetterSpacing
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TextSetLetterSpacing
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TextSetLineHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TextSetLineHeight
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    TextSetAlign
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TextSetAlign
  (JNIEnv *, jclass, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawText
 * Signature: (FFLjava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_DrawText
  (JNIEnv *, jclass, jfloat, jfloat, jstring);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawTextBox
 * Signature: (FFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_DrawTextBox
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawTextBounds
 * Signature: (FFLjava/lang/String;[F)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_DrawTextBounds
  (JNIEnv *, jclass, jfloat, jfloat, jstring, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawTextBoxBounds
 * Signature: (FFFLjava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_DrawTextBoxBounds
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jstring, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    TextMetricsGetAscender
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_TextMetricsGetAscender
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    TextMetricsGetDescender
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_TextMetricsGetDescender
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    TextMetricsGetLineHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_TextMetricsGetLineHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
