/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class flat_backend_SVG */

#ifndef _Included_flat_backend_SVG
#define _Included_flat_backend_SVG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     flat_backend_SVG
 * Method:    Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_flat_backend_SVG_Create
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    BeginFrame
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_BeginFrame
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    EndFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_EndFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    Flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    SetAntiAlias
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetAntiAlias
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     flat_backend_SVG
 * Method:    SetStroke
 * Signature: (JFIIF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetStroke
  (JNIEnv *, jclass, jlong, jfloat, jint, jint, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintLinearGradient
 * Signature: (J[FFFFFI[F[II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintLinearGradient
  (JNIEnv *, jclass, jlong, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jintArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintRadialGradient
 * Signature: (J[FFFFFI[F[II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintRadialGradient
  (JNIEnv *, jclass, jlong, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jintArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintBoxGradient
 * Signature: (J[FFFFFFFI[F[II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintBoxGradient
  (JNIEnv *, jclass, jlong, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jintArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintImage
 * Signature: (JI[FI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintImage
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintImageLinearGradient
 * Signature: (JI[F[FFFFFI[F[II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintImageLinearGradient
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jintArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintImageRadialGradient
 * Signature: (JI[F[FFFFFI[F[II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintImageRadialGradient
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jintArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintImageBoxGradient
 * Signature: (JI[F[FFFFFFFI[F[II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintImageBoxGradient
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jintArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformIdentity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformIdentity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformSet
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformSet
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    ClearClip
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_ClearClip
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    PathBegin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_PathBegin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    MoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_MoveTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    LineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_LineTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    QuadTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_QuadTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    CubicTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_CubicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    PathEnd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_PathEnd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    Rect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Rect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Ellipse
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Ellipse
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    RoundRect
 * Signature: (JFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_RoundRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontCreate
 * Signature: ([BFI)J
 */
JNIEXPORT jlong JNICALL Java_flat_backend_SVG_FontCreate
  (JNIEnv *, jclass, jbyteArray, jfloat, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    FontLoadAllGlyphs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontLoadAllGlyphs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontLoadGlyphs
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontLoadGlyphs
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     flat_backend_SVG
 * Method:    FontLoadGlyphsBuffer
 * Signature: (JLjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontLoadGlyphsBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetGlyphs
 * Signature: (JLjava/lang/String;[F)I
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontGetGlyphs
  (JNIEnv *, jclass, jlong, jstring, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetGlyphsBuffer
 * Signature: (JLjava/nio/Buffer;II[F)I
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontGetGlyphsBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetHeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetAscent
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetAscent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetDescent
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetDescent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetTextWidth
 * Signature: (JLjava/lang/String;FF)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetTextWidth
  (JNIEnv *, jclass, jlong, jstring, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetTextWidthBuffer
 * Signature: (JLjava/nio/Buffer;IIFF)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetTextWidthBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetOffset
 * Signature: (JLjava/lang/String;FFF)I
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontGetOffset
  (JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetOffsetBuffer
 * Signature: (JLjava/nio/Buffer;IIFFF)I
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontGetOffsetBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFont
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFont
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFontScale
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFontScale
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFontSpacing
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFontSpacing
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawText
 * Signature: (JFFLjava/lang/String;FII)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_DrawText
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jstring, jfloat, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawTextBuffer
 * Signature: (JFFLjava/nio/Buffer;IIFII)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_DrawTextBuffer
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jobject, jint, jint, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
