/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class flat_backend_SVG */

#ifndef _Included_flat_backend_SVG
#define _Included_flat_backend_SVG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     flat_backend_SVG
 * Method:    Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_flat_backend_SVG_Create
  (JNIEnv *, jclass);

/*
 * Class:     flat_backend_SVG
 * Method:    Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Destroy
  (JNIEnv *, jclass, jlong);


/*
 * Class:     flat_backend_SVG
 * Method:    SetDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetDebug
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     flat_backend_SVG
 * Method:    BeginFrame
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_BeginFrame
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    EndFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_EndFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    Flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    SetAntiAlias
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetAntiAlias
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     flat_backend_SVG
 * Method:    SetStroke
 * Signature: (JFIIF[FF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetStroke
  (JNIEnv *, jclass, jlong, jfloat, jint, jint, jfloat, jfloatArray, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintColor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintColor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintLinearGradient
 * Signature: (JFFFFI[FI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintLinearGradient
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintRadialGradient
 * Signature: (JFFFFFFI[FI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintRadialGradient
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintBoxGradient
 * Signature: (JFFFFFFFI[F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintBoxGradient
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    SetPaintImage
 * Signature: (JII[FI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetPaintImage
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformIdentity
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformIdentity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    TransformSet
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_TransformSet
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    ClearClip
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_ClearClip
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    PathBegin
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_PathBegin
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    MoveTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_MoveTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    LineTo
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_LineTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    QuadTo
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_QuadTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    CubicTo
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_CubicTo
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    PathEnd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_PathEnd
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    Rect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Rect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    Ellipse
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_Ellipse
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    RoundRect
 * Signature: (JFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_RoundRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontLoad
 * Signature: ([BFI)J
 */
JNIEXPORT jlong JNICALL Java_flat_backend_SVG_FontLoad
        (JNIEnv *, jclass, jbyteArray, jfloat, jint);

/*
 * Class:     flat_backend_SVG
 * Method:    FontUnload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontUnload
        (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontPaintCreate
 * Signature: (J)V
 */
JNIEXPORT jlong JNICALL Java_flat_backend_SVG_FontPaintCreate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontPaintDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontPaintDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontPaintGetAtlas
 * Signature: (J[I)V
 */
JNIEXPORT jlong JNICALL Java_flat_backend_SVG_FontPaintGetAtlas
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetGlyphShape
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_flat_backend_SVG_FontGetGlyphShape
  (JNIEnv *, jclass, jlong, jint);


/*
 * Class:     flat_backend_SVG
 * Method:    FontGetGlyph
 * Signature: (JLI[F)void
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontGetGlyph
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetGlyphsBuffer
 * Signature: (JL[I)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontGetAllCodePoints
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetHeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetAscent
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetAscent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetDescent
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetDescent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetLineGap
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetLineGap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    _FontGetGlyphCount
 * Signature: (J)F
 */
JNIEXPORT jint JNICALL Java_flat_backend_SVG_FontGetGlyphCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetTextWidth
 * Signature: (JLjava/lang/String;FF)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetTextWidth
  (JNIEnv *, jclass, jlong, jstring, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetTextWidthBuffer
 * Signature: (JLjava/nio/Buffer;IIFF)F
 */
JNIEXPORT jfloat JNICALL Java_flat_backend_SVG_FontGetTextWidthBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetOffset
 * Signature: (JLjava/lang/String;FFFZ[F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontGetOffset
  (JNIEnv *, jclass, jlong, jstring, jfloat, jfloat, jfloat, jboolean, jfloatArray cursor);

/*
 * Class:     flat_backend_SVG
 * Method:    FontGetOffsetBuffer
 * Signature: (JLjava/nio/Buffer;IIFFFZ[F)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_FontGetOffsetBuffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jfloat, jfloat, jfloat, jboolean, jfloatArray cursor);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFont
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFont
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFontScale
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFontScale
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFontSpacing
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFontSpacing
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    SetFontBlur
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_SetFontBlur
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawText
 * Signature: (JFFLjava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_DrawText
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jstring, jfloat, jfloat);

/*
 * Class:     flat_backend_SVG
 * Method:    DrawTextBuffer
 * Signature: (JFFLjava/nio/Buffer;IIFF)V
 */
JNIEXPORT void JNICALL Java_flat_backend_SVG_DrawTextBuffer
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jobject, jint, jint, jfloat, jfloat);


/*
 * Class:     flat_backend_SVG
 * Method:    ReadImage
 * Signature: ([B[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_flat_backend_SVG_ReadImage
  (JNIEnv * jEnv, jclass, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
